apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "database.name" . }}-env
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "database.labels" . | nindent 4}}
{{- with $.Values.environnements}}
data:
    {{- toYaml . | nindent 2 }}
{{- end }}