apiVersion: v1
kind: Service
metadata:
  name: {{ include "database.name" . }}-service
  labels:
    {{- include "database.labels" . | nindent 4 }}
  namespace: {{ $.Values.global.namespace }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "database.selectorLabels" . | nindent 4 }}
