apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "fullstack.name" . }}-env
    labels:
        {{- include "fullstack.labels" . | nindent 4}}
    namespace: {{ $.Values.global.namespace }}
{{- with $.Values.env }}
data: 
    {{- toYaml . | nindent 2}}
{{- end -}}