apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fullstack.name" . }}-http
  namespace: {{ $.Values.global.namespace }}
spec:
  rules:
  - host: {{ $.Values.url }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "fullstack.name" . }}-service
            port:
              number: 80   