apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullstack.name" . }}-service
  labels:
    {{- include "fullstack.labels" . | nindent 4 }}
  namespace: {{ $.Values.global.namespace }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: {{ $.Values.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "fullstack.selectorLabels" . | nindent 4 }}
