apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.name" . }}-env
  namespace: {{ $.Values.global.namespace }}
{{- with $.Values.environnements }}
data:
    {{- toYaml . | nindent 2 }}
{{- end }}