apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}-service
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
