apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "phpmyadmin.fullname" . }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "phpmyadmin.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "phpmyadmin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "phpmyadmin.labels" . | nindent 8 }}
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          env:
            - name: PMA_HOST
              value: "mysql"
            - name: PMA_PORT
              value: "3306"
          ports:
            - containerPort: 80
