apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "database.fullname" . }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
  namespace: {{ $.Values.global.namespace }}
spec:
  {{- if not $.Values.autoscaling.enabled }}
  replicas: {{ $.Values.replicaCount }}
  {{- else }}
  replicas: {{ $.Values.autoscaling.minReplicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "database.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "database.labels" . | nindent 8}}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.pullPolicy }}
          env:
            - name: MYSQL_DATABASE
              value: "library"
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_INITDB_SKIP_TZINFO
              value: "1"
            - name: MYSQL_ROOT_PASSWORD
              value: "admin"
          ports:
            - name: http
              containerPort: {{ $.Values.service.port }}
              protocol: TCP
          {{- with $.Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: {{ $.Values.volume.namepvc }}
          persistentVolumeClaim:
            claimName: {{ include "database.name" . }}-pvc
        - name: {{ $.Values.volume.namescript }}
          configMap:
            name: initialisation-db